services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.3
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data:
