services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.3
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/localhost/8000' 2>/dev/null && exit 0 || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 15
